### ISSUE TITLE
Incompatible with sprockets-rails 3.0?

### ISSUE THREAD

**Issue by dbackeus** [browserify-rails/browserify-rails#135]
After upgrading `sprockets-rails` to 3.0 I get the following boot time error:

```
.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/browserify-rails-2.2.1/lib/browserify-rails/railtie.rb:35:in `block in <class:Railtie>': undefined method `register_postprocessor' for nil:NilClass (NoMethodError)
    from .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
    from .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
    from .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
    from .rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
    from .rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
    from .rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
    from .rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
    from .rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
    from .rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
    from .rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
    from .rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
    from .rbenv/versions/2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
    from .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
    from .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
    from development/rails/mndx-web/config/environment.rb:5:in `<top (required)>'
    from development/rails/mndx-web/spec/rails_helper.rb:4:in `require'
    from development/rails/mndx-web/spec/rails_helper.rb:4:in `<top (required)>'
    from development/rails/mndx-web/spec/adapters/mndx_users_adapter_spec.rb:1:in `require'
    from development/rails/mndx-web/spec/adapters/mndx_users_adapter_spec.rb:1:in `<top (required)>'
    from .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `load'
    from .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
    from .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `each'
    from .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
    from .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:102:in `setup'
    from .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
    from .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
    from .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
    from .rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/exe/rspec:4:in `<top (required)>'
    from .rbenv/versions/2.2.3/bin/rspec:23:in `load'
    from .rbenv/versions/2.2.3/bin/rspec:23:in `<main>'
```

**Comment by cymen** [comment]
What version of browserify-rails are you using?

**Comment by cymen** [comment]
There is a bit of code that branches with a check to see if `config` responds to `assets` invocation:

```ruby
    if config.respond_to?(:assets)
      config.assets.configure do |env|
        load_granular_configuration
        env.register_postprocessor "application/javascript", BrowserifyRails::BrowserifyProcessor
      end
    else
      initializer :setup_browserify do |app|
        load_granular_configuration
        app.assets.register_postprocessor "application/javascript", BrowserifyRails::BrowserifyProcessor
      end
    end
```

Maybe with Sprockets 3.0 config does not respond to `assets`. According to the `sprocket-rails` README, it should use `env.register_preprocessor` so if config doesn't respond to `assets`, it may fall through to try to do the wrong configuration method (`app.register_preprocessor`).

**Comment by cymen** [comment]
If so, the fix may be simply changing:

`if config.respond_to?(:assets)`

To something like:

`if config.respond_to?(:assets) || is_sprockets_3_or_higher`

One would need to implement `is_sprockets_3_or_higher` of course.

**Comment by cymen** [comment]
One other thought is it could be your set of gems. Did you upgrade anything else when you upgraded `sprocket-rails`? If you haven't, it might be worth trying an upgraded `railties` too.

**Comment by dbackeus** [comment]
I got the same error on all `browserify-rails` from version 1.5.0 to 2.2.1 (the stacktrace above is 2.2.1 as can be found out through looking at the rubygems directories).

All other rails gems etc are at the latest version already.

Not sure how to reach the `env` since `config.assets.configure` will break on not responding to `.assets`.

**Comment by cymen** [comment]
I should clarify that PRs for this are welcomed if anyone has time to dig into it. I don't expect to any time soon :(.

**Comment by AndyObtiva** [comment]
I got the same issue when I upgraded from Rails 4.2.1 to 4.2.5.1.
browserify-rails is at version 1.2.0

**Comment by cymen** [comment]
Problem is here:

https://github.com/rails/sprockets-rails/issues/223

Looking into a bit more.

**Comment by cymen** [comment]
Hrm, not quite the problem but in the same area. Looks like autoprefixer ran into this. But their change is how we are configuring so it's some issue in our dependencies.

https://github.com/ai/autoprefixer-rails/issues/52

**Comment by AndyObtiva** [comment]
I was able to fix by updating "lib/browserify-rails/railtie.rb:32" from:
```
app.assets.register_postprocessor "application/javascript", BrowserifyRails::BrowserifyProcessor
```
to:
```
Sprockets.register_postprocessor "application/javascript", BrowserifyRails::BrowserifyProcessor
```

The new versions of sprockets components that came with Rails 4.2.5.1 are:
sprockets - 3.5.2
sprockets-rails -  3.0.1

**Comment by cymen** [comment]
Just upgrading to sprockets 3.5.2 seems to be fixing it for me. I'm just about to release a version w/ that but looks like 3.5.2 requires activesupport version that requires I upgrade ruby so going to take a minute.

**Comment by AndyObtiva** [comment]
Thanks a lot. You rock!

**Comment by cymen** [comment]
@AndyObtiva But that lower line is only run if config doesn't respond to assets (which it does with newer versions of things) so I think you have the same fix as me (the earlier line actually runs). So just upgrading sprockets should be :+1:.

**Comment by cymen** [comment]
@AndyObtiva Forgot to say, thanks. It is hard keeping track of these changes. Really helpful to have confirmation on right path :).

**Comment by cymen** [comment]
@AndyObtiva @dbackeus I bumped the dependency in the gemspec on sprockets up to 3.5.2 and release browserify-rails 3.0.0. Would you try the new version and confirm it works correctly for you?

Thanks!

(and reopening -- I didn't mean for this to get closed until confirmed fixed)

**Comment by AndyObtiva** [comment]
Worked for me. :+1:

**Comment by dbackeus** [comment]
Still have the very same error... same line same file but now on version 3.0.0... sprockets-rails is at 3.0.2 and sprockets at 3.5.2.

**Comment by cymen** [comment]
@dbackeus What version of Rails are you using? I tested with Rails 4.2.5.1 and it worked for me with browserify-rails 3.0.0. I'm checking Rails version with `rails -v`.

**Comment by cymen** [comment]
@dbackeus The other thing that would help is if you, with your version of Rails, can make a new project and pull in browserify-rails and add a simple module that demonstrates the failure. I'm happy to take a closer look.

I suspect the issue comes down to some of these gems following Rails releases and we'd need more stringent versioning to be compatible with all versions of Rails. I think supporting current is enough but I'm open to ideas (and solutions).

**Comment by cymen** [comment]
Closing due to lack of response. If anyone else has this issue, please reopen after pushing up an example failing Rails app to github.

**Comment by kolomeetz** [comment]
I have the same problem with browserify-rails 1.0.2, sprockets 3.7.0 and rails 4.2.7.1.

Here is the clean project with this bug: https://github.com/kolomeetz/browserify-sprockets

**Comment by cymen** [comment]
@kolomeetz browserify-rails 3+ should be compatible. I'd recommend trying the latest which is version 3.1.0. Is there a reason you're using such an old version (1.02)?

**Comment by cymen** [comment]
@kolomeetz whoops, I meant 3.2.0 not 3.1.0. Anyway, does that fix it?

**Comment by kolomeetz** [comment]
Yes, my bad. 3.2.0 works perfectly! I'm sorry for having disturbed you.

**Comment by valentin-krasontovitsch** [comment]
Got the same problem trying to run some specs in a rails eninge gem.

Using sprockets 3.6.0, sprockets-rails 3.0.4, browserify-rails 3.3.0, and no rails, since it's an engine.

https://github.com/browserify-rails/browserify-rails/issues/135#issuecomment-185390567 fixed it for me (changing line 35 in railtie.rb, the case of `config` doesn't respond to `:assets`).

If you really really want me to publish an easily reproducible example, I can try tomorrow.

**Comment by cymen** [comment]
@valentin-krasontovitsch So you still have the breakage with browserify-rails current (3.4.0)? If so, let's figure out a fix. I'm worried if I just make the change in comment 135, it'll break on earlier versions of Sprockets. The gemspec for browserify-rails has:

```
spec.add_runtime_dependency "sprockets", ">= 3.5.2"
```

So I'd want to test with Sprockets 3.5.2 and if it is broken, either figure out a work around or bump the dependency to 3.6.

**Comment by cymen** [comment]
@valentin-krasontovitsch I decided to just go for it -- can you try browserify-rails 4.0.0.b? The `.b` is for beta. I upped the Sprockets dependency to `>= 3.6.0` and changed it to use the code in comment 135. Let me know if it is good for you!

**Comment by valentin-krasontovitsch** [comment]
Sorry, was out for the day yesterday.
That totally fixed it for me, thanks a lot!
